import React from "react";
import {
  AiFillAlert,
  AiOutlineAlert,
  AiOutlineBars,
  AiOutlineControl,
  AiOutlineDashboard,
  AiOutlineUsergroupAdd,
} from "react-icons/ai";
import { HiOutlineReceiptTax, HiTemplate } from "react-icons/hi";
import {
  RiFileList3Line,
  RiFolderReceivedLine,
  RiRefund2Line,
  RiSecurePaymentLine,
  RiTodoLine,
  RiUserStarLine,
} from "react-icons/ri";
import { BiLocationPlus, BiTransfer } from "react-icons/bi";
import {
  MdOutlineAccountBalance,
  MdOutlineAccountTree,
  MdOutlineContactPhone,
  MdOutlineDns,
  MdOutlinePayments,
  MdOutlinePrivacyTip,
  MdOutlineVerified,
} from "react-icons/md";
import {
  BsArrowBarLeft,
  BsArrowBarRight,
  BsBank,
  BsBarChartLine,
  BsCalculator,
  BsChatDots,
  BsCheck2Circle,
  BsFileEarmarkCheck,
  BsPeople,
  BsQuestionDiamond,
  BsShieldLock,
} from "react-icons/bs";
import { GiLevelTwo, GiOrganigram, GiScales } from "react-icons/gi";
import {
  FaBoxes,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaRegCalendarAlt,
  FaSearchDollar,
} from "react-icons/fa";
import { FiMail, FiPlusCircle, FiSettings } from "react-icons/fi";
import { RoutePermittedRole } from "shared/constants/AppEnums";
import { getIconByName } from "meta/common/AppIcons";
import {
  TbBuildingSkyscraper,
  TbBuildingWarehouse,
  TbChartInfographic,
  TbReport,
  TbVectorTriangle,
  TbTruckDelivery,
  TbScale,
} from "react-icons/tb";
import {
  SettingOutlined,
  SwapOutlined,
  UserAddOutlined,
} from "@ant-design/icons";
import { IoJournalOutline } from "react-icons/io5";
import { GrDeliver } from "react-icons/gr";
import { CgListTree, CgUserList } from "react-icons/cg";

const routesConfig = [
  {
    id: "insights",
    permittedRole: RoutePermittedRole.user,
    // icon: <AiOutlineDashboard />,
    messageId: "sidebar.insights",
    type: "group",
    children: [
      {
        id: "vapps-dashboard",
        permittedRole: RoutePermittedRole.user,
        messageId: "sidebar.app.dashboard",
        icon: <AiOutlineDashboard />,
        path: "/insights/vapps-dashboard",
      },
    ],
  },
  {
    permittedRole: RoutePermittedRole.user,
    type: "group",
    id: "sales",
    messageId: "sidebar.apps.sales",
    // icon: <IoTrendingUpSharp />,
    path: "sales",
    children: [
      {
        id: "sales-dashboard",
        key: 111,
        permittedRole: RoutePermittedRole.user,
        title: "sales-dashboard",
        messageId: "sidebar.app.dashboard",
        path: "/sales/sales-dashboard",
        icon: <AiOutlineDashboard />,
      },
      {
        id: "Enquiry",
        key: 111,
        permittedRole: RoutePermittedRole.inquiry,
        title: "Enquiries",
        messageId: "sidebar.apps.sales.enquiry",
        path: "/sales/Enquiry",
        icon: <BsQuestionDiamond />,
      },
      {
        id: "Estimation",
        key: 110,
        permittedRole: RoutePermittedRole.estimation,
        title: "Estimation",
        messageId: "sidebar.apps.sales.estimations",
        path: "/sales/Estimation",
        icon: <BsCalculator />,
      },
      {
        id: "Quotation",
        key: 110,
        permittedRole: RoutePermittedRole.quotation,
        title: "Quotation",
        messageId: "sidebar.apps.sales",
        path: "/sales/Quotation",
        icon: <TbReport />,
      },
      {
        id: "DeliveryChallan",
        key: 110,
        permittedRole: RoutePermittedRole.quotation,
        title: "Delivery Challan",
        messageId: "sidebar.apps.deliveryChallan",
        path: "/sales/DeliveryChallan",
        icon: <GrDeliver />,
      },
      {
        id: "Estimation-template",
        key: 110,
        permittedRole: RoutePermittedRole.estTempletes,
        title: "Estimation-template",
        messageId: "sidebar.apps.sales.esitmation-template",
        path: "/sales/Estimation-template",
        icon: <HiTemplate />,
      },
      {
        id: "term-and-conditions",
        key: 110,
        permittedRole: RoutePermittedRole.user,
        title: "Term&Conditon",
        messageId: "sidebar.apps.sales.term-condition",
        path: "/sales/term-and-conditions",
        icon: <MdOutlinePrivacyTip />,
      },
    ],
  },
  {
    id: "purchase",
    permittedRole: RoutePermittedRole.user,
    title: "purchase",
    messageId: "sidebar.apps.purchase",
    //  icon: <MdAddShoppingCart />,
    path: "purchase",
    type: "group",
    key: 101,
    children: [
      {
        id: "reqforquote",
        permittedRole: RoutePermittedRole.user,
        title: "reqforquote",
        messageId: "sidebar.apps.purchase",
        path: "/purchase/reqforquote",
        icon: <FaSearchDollar />,
      },
      {
        id: "materialDemand",
        permittedRole: RoutePermittedRole.products,
        title: "materialDemand",
        key: 500,
        messageId: "sidebar.ecommerce.materialDemand",
        icon: <AiOutlineAlert />,
        path: "/Purchase/MaterialDemand",
      },
    ],
  },
  {
    id: "inventory",
    permittedRole: RoutePermittedRole.user,
    title: "inventory",
    messageId: "sidebar.apps.inventory",
    path: "inventory",
    type: "group",
    key: 101,
    children: [
      // {
      //   id: "invAlerts",
      //   permittedRole: RoutePermittedRole.products,
      //   title: "InvAlerts",
      //   key: 500,
      //   messageId: "sidebar.inventory.invAlerts",
      //   icon: <AiFillAlert />,
      //   path: "/Inventory/Alerts",
      // },
      {
        id: "invReceipts",
        permittedRole: RoutePermittedRole.products,
        title: "Receipts",
        key: 500,
        messageId: "sidebar.inventory.receipts",
        icon: <RiFolderReceivedLine />,
        path: "/Inventory/Receipts",
      },
      // {
      //   id: "invDeliveries",
      //   permittedRole: RoutePermittedRole.products,
      //   title: "Deliveries",
      //   key: 500,
      //   messageId: "sidebar.inventory.deliveries",
      //   icon: <TbTruckDelivery />,
      //   path: "/erp/Inventory/Deliveries",
      // },
      {
        id: "products",
        permittedRole: RoutePermittedRole.products,
        title: "Products",
        key: 500,
        messageId: "sidebar.ecommerce.products",
        icon: <FaBoxes />,
        path: "/inventory/products",
      },
      {
        id: "warehouse",
        permittedRole: RoutePermittedRole.products,
        title: "warehouse",
        key: 500,
        messageId: "sidebar.ecommerce.warehouse",
        icon: <TbBuildingWarehouse />,
        path: "/inventory/warehouse",
      },
      {
        id: "warehouseSetting",
        permittedRole: RoutePermittedRole.products,
        messageId: "sidebar.ecommerce.setting",
        icon: <SettingOutlined />,
        path: "/inventory/warehouseSetting",
      },
      {
        id: "binlocations",
        permittedRole: RoutePermittedRole.user,
        messageId: "sidebar.ecommerce.warehouseBinLocation",
        path: "/inventory/binlocations",
        icon: <BiLocationPlus />,
      },
      // {
      //   id: "Stock-Movements",
      //   permittedRole: RoutePermittedRole.products,
      //   title: "Stock Movements",
      //   key: 500,
      //   messageId: "sidebar.stock-movements",
      //   icon: <BiTransfer />,
      //   path: "/error-pages/coming-soon",
      // },

      // {
      //   id: "stock-adjustments",
      //   permittedRole: RoutePermittedRole.products,
      //   title: "Stock Adjustments",
      //   key: 500,
      //   messageId: "sidebar.stock-adjustments",
      //   icon: <TbVectorTriangle />,
      //   path: "/error-pages/coming-soon",
      // },
      {
        id: "uom",
        permittedRole: RoutePermittedRole.products,
        title: "Unit Of Measurment",
        key: 500,
        messageId: "sidebar.inventory.uom",
        icon: <TbScale />,
        path: "/inventory/uom",
      },
    ],
  },
  {
    id: "gatepass",
    permittedRole: RoutePermittedRole.user,
    title: "gatepass",
    messageId: "sidebar.apps.gatepass",
    // icon: <AiFillBoxPlot />,
    path: "gatepass",
    type: "group",
    key: 101,
    children: [
      {
        id: "gatedashboard",
        key: 111,
        permittedRole: RoutePermittedRole.user,
        title: "gatedashboard",
        messageId: "sidebar.apps.dashboard",
        path: "/gatepass/gatedashboard",
        icon: <AiOutlineDashboard />,
      },
      {
        id: "gatein",
        key: 111,
        permittedRole: RoutePermittedRole.user,
        title: "gatein",
        messageId: "sidebar.apps.gatein",
        path: "/gatepass/GateIn",
        icon: <BsArrowBarRight />,
      },
      {
        id: "gateout",
        key: 111,
        permittedRole: RoutePermittedRole.user,
        title: "gateout",
        messageId: "sidebar.apps.gateout",
        path: "/gatepass/GateOut",
        icon: <BsArrowBarLeft />,
      },
      {
        id: "gatesetting",
        key: 111,
        permittedRole: RoutePermittedRole.user,
        title: "gatesetting",
        messageId: "sidebar.apps.gatesetting",
        path: "/error-pages/coming-soon",
        icon: <FiSettings />,
      },
    ],
  },
  {
    id: "Quality",
    permittedRole: RoutePermittedRole.user,
    messageId: "sidebar.apps.qualityControl",
    // icon: <BsFileEarmarkCheck />,
    path: "Quality",
    type: "group",
    children: [
      {
        id: "ControlPoints",
        permittedRole: RoutePermittedRole.user,
        title: "controlPoints",
        messageId: "sidebar.apps.controlPoints",
        path: "/Quality/ControlPoints",
        icon: <AiOutlineControl />,
      },
      {
        id: "Check",
        permittedRole: RoutePermittedRole.user,
        title: "Check",
        messageId: "sidebar.apps.qualityCheck",
        path: "/Quality/Check",
        icon: <BsCheck2Circle />,
      },
      {
        id: "Team",
        permittedRole: RoutePermittedRole.user,
        title: "qualityTeam",
        messageId: "sidebar.apps.qualityTeam",
        path: "/Quality/Team",
        icon: <UserAddOutlined />,
      },
    ],
  },
  {
    id: "accounts",
    permittedRole: RoutePermittedRole.user,
    title: "accounts",
    messageId: "sidebar.apps.accounts",
    //icon: <TbChartInfographic />,
    path: "accounts",
    type: "group",
    children: [
      {
        id: "invoicing",
        permittedRole: RoutePermittedRole.user,
        title: "invoicing",
        messageId: "sidebar.apps.invoicing",
        path: "/accounts/invoicing",
        icon: <FaFileInvoiceDollar />,
      },
      {
        id: "creditNote",
        permittedRole: RoutePermittedRole.user,
        title: "CreditNote",
        messageId: "sidebar.apps.creditNote",
        path: "/accounts/creditNote",
        icon: <SwapOutlined />,
      },
      {
        id: "vendorBill",
        permittedRole: RoutePermittedRole.user,
        title: "vendorBill",
        messageId: "sidebar.apps.vendorBill",
        path: "/accounts/vendorBill",
        icon: <FaFileInvoice />,
      },
      {
        id: "refund",
        permittedRole: RoutePermittedRole.user,
        title: "Refund",
        messageId: "sidebar.apps.refund",
        path: "/accounts/Refund",
        icon: <RiRefund2Line />,
      },
      {
        id: "paymentTerms",
        permittedRole: RoutePermittedRole.user,
        title: "paymentTerms",
        messageId: "sidebar.apps.paymentTerms",
        path: "/accounts/paymentTerms",
        icon: <RiSecurePaymentLine />,
      },
      {
        id: "payments",
        permittedRole: RoutePermittedRole.user,
        title: "payments",
        messageId: "sidebar.apps.payment",
        path: "/accounts/customer/payments",
        icon: <MdOutlinePayments />,
      },
      {
        id: "vendorpayments",
        permittedRole: RoutePermittedRole.user,
        title: "payments",
        messageId: "sidebar.apps.vendorPayment",
        path: "/accounts/vendor/Payments",
        icon: <MdOutlinePayments />,
      },
      {
        id: "chartOfAccounts",
        permittedRole: RoutePermittedRole.user,
        title: "chartofaccounts",
        messageId: "sidebar.apps.chartOfAccounts",
        path: "/accounts/chartOfAccounts",
        icon: <BsBarChartLine />,
      },
      {
        id: "journalEntries",
        permittedRole: RoutePermittedRole.user,
        title: "journalEntries",
        messageId: "sidebar.apps.journalEntries",
        path: "/accounts/journalEntries",
        icon: <AiOutlineBars />,
      },
      {
        id: "journalItems",
        permittedRole: RoutePermittedRole.user,
        title: "JournnalItems",
        messageId: "sidebar.apps.journalItems",
        path: "/accounts/journalItems",
        icon: <HiOutlineReceiptTax />,
      },
      {
        id: "bankAccounts",
        permittedRole: RoutePermittedRole.user,
        title: "bankAccounts",
        messageId: "sidebar.apps.addBankAccount",
        path: "/accounts/bankAccounts",
        icon: <BsBank />,
      },
      {
        id: "accounting",
        permittedRole: RoutePermittedRole.user,
        title: "accounting",
        messageId: "sidebar.ecommerce.setting",
        path: "/accounts/accounting",
        icon: <MdOutlineVerified />,
      },

      {
        id: "tax",
        permittedRole: RoutePermittedRole.user,
        title: "tax",
        messageId: "sidebar.apps.tax",
        path: "/accounts/tax",
        icon: <HiOutlineReceiptTax />,
      },
    ],
  },
  // {
  //   id: "manufacturing",
  //   permittedRole: RoutePermittedRole.user,
  //   title: "manufacturing",
  //   messageId: "sidebar.apps.manufacturing",
  //   icon: <MdOutlinePrecisionManufacturing />,
  //   path: "manufacturing",
  //   type: "collapse",
  //   key: 101,
  //   children: [
  //     {
  //       id: "inquiry4",
  //       key: 111,
  //       permittedRole: RoutePermittedRole.inquiry,
  //       title: "Inquiries",
  //       messageId: "sidebar.apps.sales.inquiry",
  //       path: "/sales/enquiry",
  //       icon: <BsQuestionDiamond />,
  //     },
  //   ],
  // },
  {
    id: "reports",
    permittedRole: RoutePermittedRole.user,
    title: "reports",
    messageId: "sidebar.apps.reports",
    path: "reports",
    type: "group",
    key: 101,
    children: [
      {
        id: "generalLedger",
        permittedRole: RoutePermittedRole.user,
        title: "GeneralLedger",
        messageId: "sidebar.apps.generalLedger",
        path: "/reports/generalLedger",
        icon: <RiFileList3Line />,
      },
      {
        id: "trailBalance",
        permittedRole: RoutePermittedRole.user,
        title: "trailBalance",
        messageId: "sidebar.apps.trailBalance",
        path: "/reports/trailBalance",
        icon: <GiScales />,
      },
      {
        id: "partnerLedger",
        permittedRole: RoutePermittedRole.user,
        title: "PartnerLedger",
        messageId: "sidebar.apps.partnerLedger",
        path: "/reports/partnerLedger",
        icon: <CgUserList />,
      },
      {
        id: "chartOfAccounts",
        permittedRole: RoutePermittedRole.user,
        title: "chartofaccounts",
        messageId: "sidebar.apps.chartOfAccounts",
        path: "/reports/chartOfAccounts",
        icon: <CgListTree />,
      },
    ],
  },
  {
    id: "apps",
    title: "Apps",
    messageId: "sidebar.apps",
    type: "group",
    children: [
      {
        id: "contact",
        permittedRole: RoutePermittedRole.contacts,
        title: "Contacts",
        key: 500,
        messageId: "sidebar.apps.contact",
        icon: <MdOutlineContactPhone />,
        path: "/meta-workspace/contacts",
      },
      {
        id: "todo",
        title: "ToDo",
        messageId: "sidebar.apps.todo",
        count: 6,
        icon: <RiTodoLine />,
        color: "#48bb78",
        path: "/apps/todo",
      },
      {
        id: "event-management",
        permittedRole: RoutePermittedRole.events,
        messageId: "sidebar.Events",
        icon: <FaRegCalendarAlt />,
        path: "/meta-workspace/event-management",
      },
      // {
      //   id: "ticket",
      //   title: "Ticket",
      //   permittedRole: RoutePermittedRole.tasks,
      //   key: 900,
      //   messageId: "sidebar.Tasks",
      //   icon: <FaTasks />,
      //   path: "/apps/ticket/folder/all",
      // },
      {
        id: "mail",
        title: "Mail",
        messageId: "sidebar.apps.mail",
        count: 4,
        icon: <FiMail />,
        path: "/apps/mail",
      },

      {
        id: "chat",
        title: "Chat",
        icon: <BsChatDots />,
        messageId: "sidebar.apps.chat",
        path: "/apps/chat",
      },
      {
        id: "scrum-board",
        title: "Scrum Board",
        messageId: "sidebar.apps.scrumboard",
        icon: <MdOutlineDns />,
        path: "/apps/scrum-board",
      },
      {
        id: "employees",
        permittedRole: RoutePermittedRole.EMS,
        title: "employees",
        messageId: "sidebar.setting.employee",
        icon: <BsPeople />,
        path: "employees",
        type: "collapse",
        key: 100,
        children: [
          {
            id: "permission",
            key: 130,
            permittedRole: RoutePermittedRole.permissions,
            title: "Permission",
            messageId: "sidebar.setting.premission",
            path: "/admin/employees/permission",
            icon: <BsShieldLock />,
          },
          {
            id: "process",
            key: 110,
            permittedRole: RoutePermittedRole.department,
            title: "Process",
            messageId: "sidebar.setting.process",
            path: "/admin/employees/process",
            icon: <GiOrganigram />,
          },
          {
            id: "designation",
            key: 120,
            permittedRole: RoutePermittedRole.designation,
            title: "Designation",
            messageId: "sidebar.setting.designation",
            path: "/admin/employees/designation",
            icon: <RiUserStarLine />,
          },
          {
            id: "employee",
            permittedRole: RoutePermittedRole.employee,
            title: "employee",
            messageId: "sidebar.setting.employees",
            icon: <AiOutlineUsergroupAdd />,
            path: "apps/employees/employee",
            power: [4],
          },
        ],
      },
    ],
  },
];
export default routesConfig;
